tr_params:
  model_name: NormOnly
  patch_size: [64, 192, 192]
  vram_max: 24000
  batch_size: 2
  tr_val_split: 0.80
  ignore_label: null
  loss_only_on_label: false
  dilate_label: false
  # label_smoothing: 0.1
  initial_lr: 0.001
  weight_decay: 0
  max_steps_per_epoch: 1500
  max_val_steps_per_epoch: 25
  max_epoch: 500
  gradient_accumulation: 32
  load_weights_only: true
  checkpoint_path: /mnt/raid_hdd/models/normals/checkpoints/normalonly/SheetNorm_65.pth
  ckpt_out_base: /mnt/raid_hdd/models/normals/checkpoints/nofliprotate
  optimizer: AdamW
  num_dataloader_workers: 4
  tensorboard_log_dir: /home/sean/Desktop/tensorboard

model_config:
  f_maps: [32, 64, 128, 256, 320, 512]
  basic_module: "nnUNetStyleResNetBlockSE"
  se_module: 'scse'

dataset_config:
  min_labeled_ratio: 0.07
  min_bbox_percent: 0.95
  use_cache: true
  cache_file: /home/sean/Documents/GitHub/VC-Surface-Models/models/64_192_192_patch_cache_ands4.json
  volume_paths:
    - input: /mnt/raid_nvme/s1.zarr
      #sheet: /mnt/raid_nvme/datasets/1-voxel-sheet_slices-closed.zarr/0.zarr
      normals: /home/sean/Documents/GitHub/VC-Surface-Models/models/normals.zarr
      ref_label: sheet
    - input: /mnt/raid_nvme/s4.zarr
      #sheet: /home/sean/Documents/GitHub/VC-Surface-Models/models/normals/s4_sheet.zarr/volume.zarr
      normals: /home/sean/Documents/GitHub/VC-Surface-Models/models/normals/s4_normals.zarr/volume.zarr
      ref_label: sheet
  targets:
    normals:
      channels: 3
      activation: none
      weight: 1
      loss_fn: MaskedCosineLoss

inference_params:
  patch_size: [64, 192, 192]
  batch_size: 2
  checkpoint_path: /mnt/raid_hdd/models/normals/checkpoints/final_models/sheet_and_norms/SheetNorm_400.pth
  load_strict: false
  num_dataloader_workers: 16
  input_path: /mnt/raid_nvme/1.zarr
  input_format: zarr
  output_dir: /mnt/raid_hdd/s1_inference_scale1
  output_format: zarr
  output_type: np.uint8
  output_targets: [sheet, normals]
  overlap: .05
  targets:
    sheet:
      channels: 1
      activation: sigmoid
    normals:
      channels: 3
      activation: none