tr_setup:
  model_name: sheet2
  vram_max: 22000
  autoconfigure: true
  tr_val_split: 0.9
  dilate_label: false
  load_weights_only: false
  ckpt_out_base: ./checkpoints
  tensorboard_log_dir: ./logs
tr_config:
  optimizer: AdamW
  patch_size:
  - 128
  - 128
  - 128
  batch_size: 3
  max_steps_per_epoch: 500
  max_val_steps_per_epoch: 25
  max_epoch: 500
model_config:
  use_timm_encoder: false
  timm_encoder_class: null

dataset_config:
  # theres a bit of a gotcha here if using multi-channel data, the first volume listed is the one used for valid patch finding,
  # so the first one in each target needs to be single channel if 4d or only 3d
  min_labeled_ratio: 0.07
  min_bbox_percent: 0.95
  use_cache: true
  cache_file: /home/sean/Documents/GitHub/VC-Surface-Models/models/64_192_192_patch_cache_ands4.json
  targets:
    sheet:
      in_channels: 1
      out_channels: 1
      activation: none
      weight: 1
      loss_fn: BCEDiceLoss
      loss_kwargs:
        alpha: 0.5
        beta: 0.5
      volumes:
        - data_volume: "/mnt/raid_nvme/s4.zarr"
          label_volume: "/home/sean/Documents/GitHub/VC-Surface-Models/models/normals/s4_sheet.zarr/volume.zarr"
          format: "zarr_local"
        - data_volume: "/mnt/raid_nvme/s1.zarr"
          label_volume: "/mnt/raid_nvme/datasets/1-voxel-sheet_slices-closed.zarr/0.zarr"
          format: "zarr_local"
    normals:
      in_channels: 3
      out_channels: 3
      activation: none
      weight: 1
      loss_fn: MaskedCosineLoss
      volumes:
        - data_volume: "/mnt/raid_nvme/s4.zarr"
          label_volume: "/home/sean/Documents/GitHub/VC-Surface-Models/models/normals/s4_normals.zarr/volume.zarr"
          format: "zarr_local"
        - data_volume: "/mnt/raid_nvme/s1.zarr"
          label_volume: "/home/sean/Documents/GitHub/VC-Surface-Models/models/normals.zarr"
          format: "zarr_local"

inference_config:
  patch_size: [64, 192, 192]
  batch_size: 2
  checkpoint_path: /mnt/raid_hdd/models/normals/checkpoints/final_models/sheet_and_norms/SheetNorm_400.pth
  load_strict: false
  num_dataloader_workers: 16
  input_path: /mnt/raid_nvme/1.zarr
  input_format: zarr
  output_dir: /mnt/raid_hdd/s1_inference_scale1
  output_format: zarr
  output_type: np.uint8
  output_targets: [sheet, normals]
  overlap: .05
  targets:
    sheet:
      channels: 1
      activation: sigmoid
    normals:
      channels: 3
      activation: none